[Interface]
# Private key stored in sops: wg-phone1-private-key
PrivateKey = <see sops/secrets.yaml: wg-phone1-private-key>
Address = fdb4:63fa:2:aa00::f001/128

[Peer]
PublicKey = KnGSFaL9OihvQ7mSwv468V6Bhu1V9yqmd8RH4QNxoAI=
AllowedIPs = fdb4:63fa:2:aa00::/40
Endpoint = vpn.prestonperanich.com:51820
PersistentKeepalive = 25
