require("lua.items.apple")
-- require("lua.items.menus")
require("lua.items.aerospaces")
-- require("lua.items.front_app")
-- require("lua.items.spaces")
require("lua.items.calendar")
require("lua.items.widgets")
require("lua.items.media")
