_: {
  flake.modules.nixos.stalwart =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      cfg = config.features.stalwart;
      dkimVars = config.clan.core.vars.generators.stalwart-dkim;
    in
    {
      options.features.stalwart = {
        enable = lib.mkEnableOption "Stalwart mail server for outbound transactional email";

        hostname = lib.mkOption {
          type = lib.types.str;
          example = "mail.example.com";
          description = "FQDN of the mail server (used in SMTP EHLO and DKIM)";
        };

        domain = lib.mkOption {
          type = lib.types.str;
          example = "example.com";
          description = "Sending domain for outbound mail";
        };

        listenAddress = lib.mkOption {
          type = lib.types.str;
          default = "127.0.0.1";
          description = "Address for the SMTP listener (localhost-only by default)";
        };

        listenPort = lib.mkOption {
          type = lib.types.port;
          default = 25;
          description = "Port for the SMTP listener";
        };

        dkimSelector = lib.mkOption {
          type = lib.types.str;
          default = "default";
          description = "DKIM selector (used in DNS record: <selector>._domainkey.<domain>)";
        };

        dkimDnsRecord = lib.mkOption {
          type = lib.types.str;
          readOnly = true;
          description = "DKIM DNS TXT record value (generated by clan vars). Reference in cf-dns config.";
        };
      };

      config = lib.mkIf cfg.enable {
        # Generate DKIM keypair via clan vars (run: clan vars generate <hostname>)
        clan.core.vars.generators.stalwart-dkim = {
          files.private-key = { }; # secret — accessed via .path
          files.dns-record = {
            secret = false; # public key for DNS — accessed via .value
          };
          runtimeInputs = [ pkgs.openssl ];
          script = ''
            ${pkgs.openssl}/bin/openssl genrsa -out "$out"/private-key 2048 2>/dev/null
            ${pkgs.openssl}/bin/openssl rsa \
              -in "$out"/private-key \
              -pubout -outform der 2>/dev/null \
              | ${pkgs.openssl}/bin/openssl base64 -A \
              > "$out"/dns-record
          '';
        };

        # Expose the full DNS TXT record value for use in machine config
        features.stalwart.dkimDnsRecord = "v=DKIM1; k=rsa; p=${dkimVars.files.dns-record.value}";

        services.stalwart = {
          enable = true;

          credentials = {
            "dkim-key" = dkimVars.files.private-key.path;
          };

          settings = {
            server.hostname = cfg.hostname;

            # Localhost-only SMTP listener — accepts mail from local services only
            server.listener.smtp = {
              protocol = "smtp";
              bind = "${cfg.listenAddress}:${toString cfg.listenPort}";
              tls.implicit = false;
            };

            # Storage — RocksDB (minimal, all-in-one)
            store.db = {
              type = "rocksdb";
              path = "%{base_path}%/db";
              compression = "lz4";
            };

            storage = {
              data = "db";
              fts = "db";
              blob = "db";
              lookup = "db";
              directory = "internal";
            };

            directory.internal = {
              type = "internal";
              store = "db";
            };

            # Relay policy — accept from localhost, reject everything else
            session.rcpt.relay = [
              {
                "if" = "remote_ip == '127.0.0.1'";
                "then" = true;
              }
              { "else" = false; }
            ];

            # Outbound routing — deliver via MX lookup
            queue.outbound.hostname = cfg.hostname;

            queue.routing.default = {
              protocol = "smtp";
              tls = {
                starttls = "require";
                allow-invalid-certs = false;
              };
            };

            # DNS resolver
            resolver.type = "system";

            # Logging
            tracer.stdout = {
              type = "stdout";
              level = "info";
              enable = true;
            };

            # DKIM signing for outbound mail
            signature.dkim = {
              private-key = "%{file:/run/credentials/stalwart.service/dkim-key}%";
              inherit (cfg) domain;
              selector = cfg.dkimSelector;
              headers = [
                "From"
                "To"
                "Date"
                "Subject"
                "Message-ID"
              ];
              algorithm = "rsa-sha256";
              canonicalization = "relaxed/relaxed";
              expire = "10d";
            };

            auth.dkim.sign = [
              {
                "if" = "listener == 'smtp'";
                "then" = "['dkim']";
              }
              { "else" = false; }
            ];
          };
        };
      };
    };
}
