#!/usr/bin/env lua

-- Add the config directory to the package path for lua modules
local config_dir = os.getenv("HOME") .. "/.config/sketchybar"
package.path = package.path .. ";" .. config_dir .. "/?.lua;" .. config_dir .. "/?/init.lua"

-- Require the sketchybar module
sbar = require("sketchybar")
_G.sbar = sbar -- Make sbar available globally to all required modules

-- Set base_dir for helper binaries
base_dir = config_dir .. "/lua"
_G.base_dir = base_dir -- Make base_dir available globally to all required modules

-- Bundle the entire initial configuration into a single message to sketchybar
-- This improves startup times drastically
sbar.begin_config()
require("lua.init")
sbar.hotload(true)
sbar.end_config()

-- Run the event loop of the sketchybar module
sbar.event_loop()
