set -g default-terminal screen-256color
set -ag terminal-overrides ",alacritty:RGB"

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

unbind r
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf

# renumber windows when a window is closed
set -g renumber-windows on
# set terminal title
set -g set-titles on
# slightly longer pane indicators display time
set -g display-panes-time 800
# slightly longer status messages display time
set -g display-time 1000
# redraw status line every 10 seconds
set -g status-interval 10
# reduce escape time
set -s escape-time 10

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind > swap-pane -D       # swap current pane with the next one
bind < swap-pane -U       # swap current pane with the previous one

# maximize current pane
bind + run 'cut -c3- $XDG_CONFIG_HOME/tmux/tmux.conf | sh -s _maximize_pane "#{session_name}" #D'

# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# window navigation
unbind n
unbind p
bind -r C-h previous-window # select previous window
bind -r C-l next-window     # select next window
bind Tab last-window        # move to last active window

# toggle mouse
bind m run "cut -c3- $XDG_CONFIG_HOME/tmux/tmux.conf | sh -s _toggle_mouse"

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

set -g status-style bg=black,fg=cyan

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-copycat'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# ==============================================
# ===   Nesting local and remote sessions     ===
# ==============================================
# see: toggle on/off all keybindings · Issue #237 · tmux/tmux - https://github.com/tmux/tmux/issues/237

# Also, change some visual styles when window keys are off
bind -T root F12  \
    set prefix None \;\
    set key-table off \;\
    set status-style "bg=black,fg=orange" \;\
    if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
    refresh-client -S \;\

bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  set -u status-style \;\
  refresh-client -S

set-environment -g TMUX_PLUGIN_MANAGER_PATH "$XDG_DATA_HOME/tmux/plugins"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "$XDG_DATA_HOME/tmux/plugins/tpm/tpm"
